### ISSUE TITLE
Where is "caption_flickr30k.json"

### ISSUE THREAD

**Issue by existence23** [facebookresearch/grounded-video-description#1]
Hi, I'm using the flickr30k branch to try this repo.
 in the "misc/utils.py" file, line 349, 
annFile = 'tools/coco-caption/annotations/caption_flickr30k.json'
when I test the environment, the error shows that I don't have the caption_flickr30k.json file. Can I ask that where is this file?

Another question is , in the "prepro/prepro_det.py" file, line 31
    det_file = json.load(open('data/flickr30k/flickr30k_detection.json'))
the error shows that I don't have data/flickr30k/flickr30k_detection.json.
BTW, the same file, line 15, I think it should be changed to 'flickr30k' instead of 'coco'

**Comment by LuoweiZhou** [comment]
@existence23 `caption_flickr30k.json` should be downloaded by the [download_all.sh](https://github.com/facebookresearch/grounded-video-description/blob/flickr_branch/tools/download_all.sh) script. For questions related to `prepro/prepro_det.py`, you can refer to [NBT](https://github.com/jiasenlu/NeuralBabyTalk). As far as I know, I did not see `flickr30k_detection.json`. However, `prepro/prepro_det.py` is deprecated in our repo and will be removed. We use [Detectron](https://github.com/LuoweiZhou/Detectron) to extract feature, similar to what is in [Pythia](https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py).

**Comment by existence23** [comment]
Hi, thank you for your reply! I did finish the download_all.sh, I don't know why that file missing. I re-download again. Sorry for my mistake.

**Comment by LuoweiZhou** [comment]
@existence23 no worries. Thanks for your interest.
