### ISSUE TITLE
Pre-trained models using Transformer for unsupervised mode?

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/grounded-video-description#13]
Hi, is there any pre-trained model of transformer under unsupervised mode available? Thanks.

**Comment by LuoweiZhou** [comment]
@CaesarPan We do not have any pre-trained model on Masked Transformer as this part of the code is for reference only. The implementation here is a variant of the original model as
i) our Transformer encoder is applied on [region features](https://github.com/facebookresearch/grounded-video-description/blob/master/misc/model.py#L551),
ii) our Transformer [decoder](https://github.com/facebookresearch/grounded-video-description/blob/master/misc/model.py#L413) takes the [last hidden state](https://github.com/facebookresearch/grounded-video-description/blob/master/misc/transformer.py#L254) from Transformer encoder and sometimes the frame-wise video feature,
while in Masked Transformer, hidden states from all the Transformer encoder (on top of frame-wise features) are feed into Transformer decoder.
For pre-trained Transformer models on captioning, you can refer to this new repo: https://github.com/LuoweiZhou/VLP
