### ISSUE TITLE
Pre-trained model GVD on test-split

### ISSUE THREAD

**Issue by Jyoti04-demo** [facebookresearch/grounded-video-description#15]
Hello All,

I am trying to reproduce the results of ActivityNet-Entities using Pre-trained model for "test-split",
But I am getting the following results :

**--------------------------------------------------------------------------------
The overall localization accuracy is nan
--------------------------------------------------------------------------------
Number of videos in the reference: 0, number of videos in the submission: 1302
Number of groundable objects in this split: 0
--------------------------------------------------------------------------------
The overall localization accuracy is nan
--------------------------------------------------------------------------------

**Results Summary (GT sent):
The averaged attention / grounding box accuracy across all classes is: nan / nan
The averaged classification accuracy across all classes is: 0.0000****

Can please someone explains the reason for 0 accuracy, whether I am missing some parameter or file to pass?

**Comment by LuoweiZhou** [comment]
Sorry for the delay. I have been traveling and will look into this issue early next week. Please stay tuned.

**Comment by LuoweiZhou** [comment]
@Jyoti04-demo It says here `Number of videos in the reference: 0`, so the data loader cannot read the video (features). Could you make sure you have put feature files under the correct path?
