### ISSUE TITLE
Attention and Grounding Accuracy Metrics

### ISSUE THREAD

**Issue by aligholami** [facebookresearch/grounded-video-description#16]
Hi and thanks for this great work.

I am curious about the metrics that you used to evaluate the attention and grounding performance. As stated in the table 2 of the GVD paper, the attention and grounding accuracies are the object localization accuracies for attention and grounding. Is "object localization" accuracy the same as IoU ratios in this case? Can you please provide some links/figures to the actual definition of attention and grounding accuracy? To the best of my knowledge, there was not a clear one in the paper.

Regards,
Ali

**Comment by LuoweiZhou** [comment]
@aligholami The attention and grounding accuracies are the object localization accuracies for attention and grounding at 50% IoU. Details regarding the metrics are in `Sec. 5.1 Metrics` and `Sec. A.2.` in the Appendix.
