### ISSUE TITLE
Beam search broken

### ISSUE THREAD

**Issue by wildermuthn** [facebookresearch/grounded-video-description#18]
There are a few problems I found with beam search simply not working. The first is the inclusion of two extra parameters in the call to core:

https://github.com/facebookresearch/grounded-video-description/blob/eae96ba8db084e9cec6aac5cb920112f761f3ac5/misc/CaptionModelBU.py#L179

`core` is being called with two extra parameters, causing beam search to fail. The extra parameters appear to be `Variable(beam_pool_feats.data.new(beam_size, rois_num).fill_(0))` and `self`. I've looked at the rest of the code but don't see any variant core models that would take this extra parameters, and `self` doesn't make sense regardless. 

Even after removing those two variables (which isn't a great idea, as I assume there is a reason for the Variable, the beam search function itself returns an incorrect number of params:

https://github.com/facebookresearch/grounded-video-description/blob/7247780167d01505c9ed495ed1112ec0799f4614/misc/model.py#L742

It returns 3, whereas the normal `_sample` function returns 4:

https://github.com/facebookresearch/grounded-video-description/blob/7247780167d01505c9ed495ed1112ec0799f4614/misc/model.py#L624

I'd love to understand better how beam search should work, and how I'd go about fixing it. Thanks!

**Comment by wildermuthn** [comment]
I should add that I reworked the code for inference on a single video segment, and in doing so removed some assertions: 

https://github.com/facebookresearch/grounded-video-description/blob/f4d6a3ed0e5025e1644946337bb4e2e9f5c3624c/main.py#L352

Is it that beam search is fundamentally unsupported, or just currently? Thanks!

**Comment by LuoweiZhou** [comment]
@wildermuthn Yes, you are right. `Variable(beam_pool_feats.data.new(beam_size, rois_num).fill_(0))` and `self` are both redundant and should be removed. Beam search was deprecated in our final experiments as it led to no significant performance boost and we failed to keep it up-to-date.

I believe if you remove these two variables and figure out how to return `sim_mat_static` in [_sample_beam](https://github.com/facebookresearch/grounded-video-description/blob/7247780167d01505c9ed495ed1112ec0799f4614/misc/model.py#L742), the code should still function well, at least for the caption generation part. For the grounding part, the code has not incorporated some late changes and requires some tweaks on `att2` and `att2_weight`.

**Comment by LuoweiZhou** [comment]
Please feel free to submit PR and I will review the commits accordingly. Thanks in advance!
