### ISSUE TITLE
Why 100% teacher forcing?

### ISSUE THREAD

**Issue by aligholami** [facebookresearch/grounded-video-description#19]
Based on what I get from the code, the teacher forcing ratio is set to 100% in both training and validation modes. Shouldn't the teacher forcing ratio to be set to 0 during validation? Otherwise, we are not really validating the model. Also, I don't understand why the teacher forcing should be 100% for training either, just because it makes the model perform better?

Regards,
Ali

**Comment by LuoweiZhou** [comment]
@aligholami Could you refer to the code you have questions about so I can have a more prompt response. During training (image/video description), we usually have 100% teacher forcing as it gives the best inference sampling results during validation/testing (despite the discrepency in the two modes).
