### ISSUE TITLE
Image Data and Visualization

### ISSUE THREAD

**Issue by jeffz0** [facebookresearch/grounded-video-description#2]
Hi!

I'm trying to visualize some of the results by using "--vis_attn", but I am unsure where the image_path data is stored. Additionally, are there any other visualization scripts you used to visualize results? 

Much appreciated!

Jeff

**Comment by LuoweiZhou** [comment]
Hi Jeff, due to copyright considerations, we will not release the video frames. Please email Luowei (luozhou@umich.edu) for further instructions on getting the frames. We do not have other visualization scripts to release.
