### ISSUE TITLE
Masked Transformer in this repo

### ISSUE THREAD

**Issue by TheShadow29** [facebookresearch/grounded-video-description#21]
Hi. Thanks for this amazing repository. 

I was looking at the code for masked transformer and in the readme, I find that the "captioning-only" model can be obtained by configuring `--att_model` in this implementation. 

Could you clarify how one would go about doing that?

**Comment by LuoweiZhou** [comment]
@TheShadow29 This implementation is for reference only, you can refer to this issue: https://github.com/facebookresearch/grounded-video-description/issues/13

**Comment by TheShadow29** [comment]
@LuoweiZhou thanks for the quick response. To clarify, is the `unsupervised` model in this repo similar to masked transformer using ground-truth segments?

**Comment by LuoweiZhou** [comment]
Yes. `unsupervised` indicates no bounding box supervision.
