### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by niu1970** [facebookresearch/grounded-video-description#25]
Hello!When I ran Main.py using your pre-training model, the configuration and errors were as follows:
D:\Anaconda2\envs\py36\python.exe D:/grounded-video-description-master/main.py --path_opt cfgs/anet_res101_vg_feat_10x100prop.yml --batch_size 1 --cuda --num_workers 0 --max_epoch 1 --inference_only --start_from save/anet-sup-0.05-0-0.1-run3 --id anet-sup-0.05-0-0.1-run3 --val_split testing --densecap_references anet_entities_test_1.json anet_entities_test_2.json --densecap_verbose --seq_length 20 --language_eval --eval_obj_grounding --obj_interact
D:/grounded-video-description-master/main.py:525: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  options_yaml = yaml.load(handle)
DataLoader loading json file:  data/anet/dic_anet.json
vocab size is  4905
DataLoader loading input file:  data/anet/cap_anet_trainval.json
DataLoader loading grounding file:  tools/anet_entities/data/anet_entities_cleaned_class_thresh50_trainval.json
DataLoader loading proposal file:  data/anet/anet_detection_vg_fc6_feat_100rois.h5
assigned 0 segments to split training
DataLoader loading json file:  data/anet/dic_anet.json
vocab size is  4905
DataLoader loading input file:  data/anet/cap_anet_trainval.json
DataLoader loading grounding file:  tools/anet_entities/data/anet_entities_cleaned_class_thresh50_trainval.json
DataLoader loading proposal file:  data/anet/anet_detection_vg_fc6_feat_100rois.h5
assigned 0 segments to split testing
THCudaCheck FAIL file=C:/ProgramData/Miniconda3/conda-bld/pytorch_1524543037166/work/aten/src/THC/THCTensorRandom.cu line=25 error=30 : unknown error
Traceback (most recent call last):
  File "D:/grounded-video-description-master/main.py", line 576, in <module>
    segs_feat = segs_feat.cuda()
RuntimeError: cuda runtime error (30) : unknown error at C:/ProgramData/Miniconda3/conda-bld/pytorch_1524543037166/work/aten/src/THC/THCTensorRandom.cu:25

Process finished with exit code 1

Looking forward to your reply!

**Comment by IT980809** [comment]
您用的是什么软件执行的啊？

**Comment by LuoweiZhou** [comment]
@duola1970 From the log output "assigned 0 segments [...]", it seems the path to your feature files is incorrect. Please check you have configured properly [here](https://github.com/facebookresearch/grounded-video-description/blob/master/cfgs/anet_res101_vg_feat_10x100prop.yml).

**Comment by niu1970** [comment]
OK,thank you!
