### ISSUE TITLE
Uniform sampling script?

### ISSUE THREAD

**Issue by ghost** [facebookresearch/grounded-video-description#26]
Hi Louwei, thanks for the great work and code!

I really appreciate it if you provide the uniform sampling script that you use to take some frames from the videos. I need to extract features directly from the frames, and I want my pipeline to be in accordance to what you have done. Thank you so much :)

**Comment by LuoweiZhou** [comment]
@aligholami You will find it in step 11 in https://github.com/LuoweiZhou/detectron-vlp/issues/5#issuecomment-643349546
