### ISSUE TITLE
conda environment 

### ISSUE THREAD

**Issue by Mollylulu** [facebookresearch/grounded-video-description#27]
hi, when I create python3 env, I got the following issue. Could you help me solve this prob?

```
Solving environment: failed
ResolvePackageNotFound:
  - python==3.7.6=h0371630_1
```

**Comment by LuoweiZhou** [comment]
@Mollylulu You could try other workable python3.7 versions.

**Comment by Mollylulu** [comment]
> @Mollylulu You could try other workable python3.7 versions.

thx, I will try it.
