### ISSUE TITLE
Pre-trained model on VG for region proposal extraction

### ISSUE THREAD

**Issue by Xun-Yang** [facebookresearch/grounded-video-description#3]
Hi, can you share your well pretrained model on the Visual Genome dataset for region proposal extraction?

**Comment by LuoweiZhou** [comment]
@Xun-Yang our code is based on [Detectron](https://github.com/facebookresearch/Detectron) and you can refer to the feature extraction of [Pythia](https://github.com/facebookresearch/pythia/blob/master/tools/extract_features.py) for an example. Our original code is based on a private repo which we do not plan to release. Please email Luowei (luozhou@umich.edu) for details on the pre-trained model and config file.

**Comment by LuoweiZhou** [comment]
More detailed instruction is here: https://github.com/facebookresearch/grounded-video-description/issues/5

**Comment by LuoweiZhou** [comment]
The region feature extraction code is now available here: https://github.com/LuoweiZhou/detectron-vlp
