### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by louyu-cc** [facebookresearch/grounded-video-description#30]
When I run following command come accross the issue:
```
python main.py --batch_size 100 --cuda --num_workers 6 --max_epoch 50 --inference_only \
    --start_from save/anet-sup-0.05-0-0.1-run1 --id anet-sup-0.05-0-0.1-run1 \
    --seq_length 20 --language_eval --eval_obj_grounding --obj_interact
```
```
index: 420, similarity: 0.58, swimming, number
index: 424, similarity: 0.46, he, camera
Loading the model save/anet-sup-0.05-0-0.1-run1/model-best.pth...
Finetune param: vis_embed.0.weight
Finetune param: ctx2pool_grd.0.weight
Finetune param: ctx2pool_grd.0.bias
Use adam as optmization method
428 classes have the associated lemma word!
Traceback (most recent call last):
  File "main.py", line 696, in <module>
    lang_stats = eval(epoch, opt)
  File "main.py", line 333, in eval
    data = data_iter_val.next()
  File "/home/louyu/miniconda3/envs/torch11/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/louyu/miniconda3/envs/torch11/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/louyu/miniconda3/envs/torch11/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/louyu/miniconda3/envs/torch11/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/louyu/DATA/grounded-video-description/misc/dataloader_anet.py", line 193, in __getitem__
    assert(num_proposal == region_feature.shape[0])
AssertionError
```
I am using RTX 2070 so I am using cuda 10.2 and can't install cuda 9, so any ideas about this issue?

**Comment by yimikai** [comment]
same situation. Have you solved it?

**Comment by louyu-cc** [comment]
> same situation. Have you solved it? 

not yet

**Comment by LuoweiZhou** [comment]
@yimikai @Louyu666 Just to confirm, are you using image features extracted by yourself or the one provided in this repo? Also, could you print out the value of `num_proposal` and `region_feature.shape[0]` to see why they are not matching? Thanks.

**Comment by pandababyer** [comment]
@LuoweiZhou @Louyu666 @yimikai  Hi, I have the same issue and i think it is the problem how the anet_detection_vg_fc6_feat_100rois.h5 is load . the num_proposals should be 1000 but if you load the h5 file with driver='core' in dataloader_anet.py line 97 
 https://github.com/facebookresearch/grounded-video-description/blob/2667e216223a63cdc91b616a34f4c046e507a1dc/misc/dataloader_anet.py#L97
the num_proposals will be different. I do a test and the picture can be more clear:

![image](https://user-images.githubusercontent.com/24407543/99020548-d04f1600-2599-11eb-921e-a68a54e7433c.png)

**Comment by LuoweiZhou** [comment]
@pandababyer Thanks for your feedback. The `driver` option might indeed be the issue here. Are you loading the .h5 file provided in the repo or generated by yourself on your customized dataset through the `detectron-vlp` repo?

**Comment by pandababyer** [comment]
@LuoweiZhou  The .h5 file is provided by your repo.

**Comment by LuoweiZhou** [comment]
This appears to be an issue with recent h5py updates/configs. For now, make sure you stick with the same h5py version from here: https://github.com/facebookresearch/grounded-video-description/blob/master/cfgs/conda_env_gvd_py3.yml#L50
