### ISSUE TITLE
Viewing results

### ISSUE THREAD

**Issue by nikky4D** [facebookresearch/grounded-video-description#31]
Hi,

where could I see the sentences generated by the model? 

I downloaded the pretrained models. Using the evaluation code, I can run the evaluation script. However, I don't see the caption results generated by the model. What folder would it be in? or is it not saved? 

Thanks

Nikky

**Comment by LuoweiZhou** [comment]
https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L420
