### ISSUE TITLE
i can't fine the grd_reference file

### ISSUE THREAD

**Issue by wangying1586** [facebookresearch/grounded-video-description#33]
In utils.py, where is the grd_reference file about default='tools/anet_entities/data/anet_entities_cleaned_class_thresh50_trainval.json'  
Please tell me ~~~~  
Thank you very much.
i can't find it where it is

**Comment by LuoweiZhou** [comment]
@wangying1586 Sorry for the late response. Just in case you haven't figured it out yet, we mentioned [here](https://github.com/facebookresearch/grounded-video-description#-training-and-validation): "[...] Link tools/anet_entities to your ANet-Entities dataset root location". The ANet-Entities dataset repo is at [here](https://github.com/facebookresearch/ActivityNet-Entities).
