### ISSUE TITLE
proposals vs. bboxs

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/grounded-video-description#4]
Hi Luowei,

Thanks for sharing this wonderful codebase and dataset! I see there're both proposal and bounding box annotations provided. I'm wondering what's the difference between these two? Thanks!

**Comment by LuoweiZhou** [comment]
@CaesarPan thanks for your interest in our work. Proposals are generated by off-the-shelf object detectors (e.g., [Faster R-CNN](https://github.com/facebookresearch/Detectron)) on any arbitrary input video. Bounding box annotations are the ground-truth bounding box coordinates annotated by our in-house annotators. During testing, box annotations are used as grounding evaluation reference.

**Comment by CaesarPan** [comment]
@LuoweiZhou Thanks for your fast reply. Just for clarification, during training the box annotations are also used as supervision right?

**Comment by LuoweiZhou** [comment]
Yes, for the supervised methods. The unsupervised baseline has no box supervision during training.

**Comment by CaesarPan** [comment]
But for the region classification loss as well as the grounding loss, they also require box supervision. Is that correct?

**Comment by LuoweiZhou** [comment]
Yes, all three proxy tasks: supervised attention, supervised grounding, and region classification.

**Comment by CaesarPan** [comment]
Yes, so if we only remove supervised attention for the unsupervised model, I think it still needs box supervision or no?

**Comment by LuoweiZhou** [comment]
No, the unsupervised baseline has none of the three proxy tasks.

**Comment by CaesarPan** [comment]
Got it. Thanks very much for your time!
