### ISSUE TITLE
some feature file was lossed in fc6_feat_100rois and rgb_motion_1d

### ISSUE THREAD

**Issue by ShiYaya** [facebookresearch/grounded-video-description#5]
### so i wish you can check your upload file when you have free time, 

DataLoader loading json file:  data/anet/dic_anet.json
vocab size is  4905
DataLoader loading json file:  data/anet/cap_anet_trainval.json
DataLoader loading json file:  data/anet/anet_captions_all_splits.json
DataLoader loading proposal file:  data/anet/anet_detection_vg_fc6_feat_100rois.h5
a file lossed: data/anet/fc6_feat_100rois/v_---9CpRcKoU_segment_00.npy
a file lossed: data/anet/fc6_feat_100rois/v_---9CpRcKoU_segment_01.npy
a file lossed: data/anet/fc6_feat_100rois/v_---9CpRcKoU_segment_02.npy
a file lossed: data/anet/fc6_feat_100rois/v_cxIfpBvuk0E_segment_08.npy
a file lossed: data/anet/fc6_feat_100rois/v_cxIfpBvuk0E_segment_09.npy
a file lossed: data/anet/fc6_feat_100rois/v_cxIfpBvuk0E_segment_10.npy
a file lossed: data/anet/fc6_feat_100rois/v_kBUDMFgWO9I_segment_03.npy
a file lossed: data/anet/rgb_motion_1d/xeOHoiH-dmo_bn.npy
a file lossed: data/anet/rgb_motion_1d/xeOHoiH-dmo_bn.npy
a file lossed: data/anet/rgb_motion_1d/xeOHoiH-dmo_bn.npy
a file lossed: data/anet/fc6_feat_100rois/v_tD30qafrkhM_segment_10.npy
a file lossed: data/anet/fc6_feat_100rois/v_tD30qafrkhM_segment_11.npy
a file lossed: data/anet/fc6_feat_100rois/v_tD30qafrkhM_segment_12.npy
a file lossed: data/anet/fc6_feat_100rois/v_tD30qafrkhM_segment_13.npy
a file lossed: data/anet/fc6_feat_100rois/v_vdYFwqfqgJA_segment_02.npy
a file lossed: data/anet/fc6_feat_100rois/v_sjyZWmvTGA4_segment_00.npy
a file lossed: data/anet/fc6_feat_100rois/v_sjyZWmvTGA4_segment_01.npy
a file lossed: data/anet/fc6_feat_100rois/v_sjyZWmvTGA4_segment_02.npy
a file lossed: data/anet/fc6_feat_100rois/v_sjyZWmvTGA4_segment_03.npy
a file lossed: data/anet/fc6_feat_100rois/v_sjyZWmvTGA4_segment_04.npy
a file lossed: data/anet/rgb_motion_1d/iVVatZsgnGo_bn.npy
a file lossed: data/anet/rgb_motion_1d/iVVatZsgnGo_bn.npy
a file lossed: data/anet/rgb_motion_1d/iVVatZsgnGo_bn.npy
a file lossed: data/anet/fc6_feat_100rois/v_E33xUgVqEH0_segment_01.npy
training videos: 10005
assigned 37397 segments to split training
DataLoader loading json file:  data/anet/dic_anet.json
vocab size is  4905
DataLoader loading json file:  data/anet/cap_anet_trainval.json
DataLoader loading json file:  data/anet/anet_captions_all_splits.json
DataLoader loading proposal file:  data/anet/anet_detection_vg_fc6_feat_100rois.h5
a file lossed: data/anet/rgb_motion_1d/j73Wh1olDsA_bn.npy
a file lossed: data/anet/rgb_motion_1d/j73Wh1olDsA_bn.npy
a file lossed: data/anet/rgb_motion_1d/j73Wh1olDsA_bn.npy
validation videos: 2459
assigned 8771 segments to split validation

**Comment by LuoweiZhou** [comment]
@ShiYaya Unfortunately, these feature files are missing due to feature extraction errors and we do not have them either. But you can try generating the frame-wise feature on your own with this [code](https://github.com/LuoweiZhou/anet2016-cuhk-feature).

**Comment by LuoweiZhou** [comment]
(Updates) The Detectron config file and checkpoint for region feature extraction are here (features in dir `fc6_feat_100rois`):
http://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/e2e_faster_rcnn_X-101-64x4d-FPN_2x.pkl  
http://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/e2e_faster_rcnn_X-101-64x4d-FPN_2x.yaml
Detectron docker image:
https://hub.docker.com/r/housebw/detectron
The feature extraction script is based on:
https://github.com/facebookresearch/pythia/blob/7e593fc66ad74e22d218300df692e254f53d9375/pythia/scripts/features/extract_features.py

**Comment by LuoweiZhou** [comment]
The region feature extraction code is now available here: https://github.com/LuoweiZhou/detectron-vlp
