### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by FrankChJ** [facebookresearch/grounded-video-description#7]
Hi, I am confused about the feature extraction process.
How can I use this model on other videos ?

**Comment by LuoweiZhou** [comment]
@FrankChJ Please see the followings for the Detectron config/model files:
http://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/e2e_faster_rcnn_X-101-64x4d-FPN_2x.pkl  
http://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/e2e_faster_rcnn_X-101-64x4d-FPN_2x.yaml

**Comment by LuoweiZhou** [comment]
More detailed instruction is here: https://github.com/facebookresearch/grounded-video-description/issues/5
