### ISSUE TITLE
Pre-trained model for GVD

### ISSUE THREAD

**Issue by TheShadow29** [facebookresearch/grounded-video-description#8]
Hi. Thank you for the amazing repository. I see that the arguments for the pretrained models are 
 `w_att2=0.05, w_grd=0, w_cls=0.1`. If I understand correctly, this would correspond to the third-last row in Table 2 of your paper (https://arxiv.org/pdf/1812.06587.pdf). Is that correct?

If so, could you share the pretrained model for GVD (last row in Table 2 of your paper).

**Comment by LuoweiZhou** [comment]
@TheShadow29 Sorry for the delay. We will retrieve the checkpoints from our backup storage. Please stay tuned.

**Comment by LuoweiZhou** [comment]
It's now available here: https://dl.fbaipublicfiles.com/ActivityNet-Entities/ActivityNet-Entities/anet-sup-0.1-0.1-0.1.tar.gz
