### ISSUE TITLE
Does this work use pretrained word embedding for word representation?

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/grounded-video-description#9]
Hi there,

I see glove is used to find the nearest neighbor of VG classes, but I didn't see it being used to initialize the word embeddings. Or this work initializes the words as one-hot encodings and train the embedding from scratch?

**Comment by LuoweiZhou** [comment]
Hi @CaesarPan, yes, we train the word embeddings from scratch.

**Comment by CaesarPan** [comment]
Gotcha. Thanks!
